import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UIProvider } from "../context/UIProvider";
import Navbar from "@/layouts/Navbar";
import WalletProvider from "@/context/WalletProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <UIProvider>
          <WalletProvider>
            <Navbar />
            {children}
          </WalletProvider>
        </UIProvider>
      </body>
    </html>
  );
}
